#!/usr/bin/env bash
#Write a Bash script that gives the content of the file /etc/passwd
fileName="/etc/passwd"
while IFS=: read -r username password userid groupid comment homedir cmdshell
do
	echo "$username, $userid, $comment $homedir"
done < $fileName
