#!/usr/bin/env bash
#display different word accoding to the code
count=1
while [ $count -le 10 ]
do
  if [ $count -eq 4 ]; do
    echo "Bad Luck"
  elif [ $count -eq 8 ]; do
    echo "Good Luck"
  else
    echo "Best School"
do
  count=$((count + 1))
done
