#!/usr/bin/env bash                                                                                          
# Initialize the hours and minutes variables                                                                 
hour=0                                                                                                       
minute=1
echo "Hours : $hour"
while [ $hour -lt 13 ]
do
	echo "$hour"
	hour=$(( $hour + 1))
done
echo "Minutes : $minute"
while [ $minute -lt 60 ]
do
	echo "$minute"
	minute=$(( $minute + 1))
done
